### ISSUE TITLE
Player doesn't appear on the first puzzle if it’s in the script

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/craft#155]
It only works if it is viewed at the /levels/ route

**Comment by Hamms** [comment]
For some context:

For these HoC levels, we do some pretty aggressive optimization to make sure that we only load exactly the assets necessary for each level. For "Events" levels, the way this was implemented was by hard-coding a list of the assets needed, indexed by the level's position within a script. So when we load up an Events level and note that it's the first level in the script, we know exactly what assets to load and load only those.

The first level of the craft17 script was implemented as an Events level, not an Agent level. This is probably because the Agent doesn't show up until after you complete the level, and Agent levels assume an Agent present from the start. The linked PR simply makes it so that Agent levels will only start with an Agent if you specify an Agent Start Position, so the level in question can be updated to be an Agent level. This should fix the problem.
