### ISSUE TITLE
Agent can be moved with WASD (in levels)

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#163]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/2

After a player presses the Run button to run their code, the Agent and Steve can still be simultaneously controlled with WASD which can lead some wonky behavior (and cheating as many puzzles would not need code anymore).

Steps:
1. Load any level with the Agent
2. Press the RUN button
3. Use WASD to move Steve around the level
4. Observe Steve and Agent movement

Attachments:
[HoC_Agent_MovesWithWASD.zip](https://github.com/code-dot-org/craft/files/1349866/HoC_Agent_MovesWithWASD.zip)

**Comment by Hamms** [comment]
This is strictly a property of the 2-D Craft Playground, and is there for the tester's convenience. In the actual level environment, the Agent is only controllable via Blockly blocks.

**Comment by WilliamHarmonMS** [comment]
@Hamms So that link ( https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/2 )
is not reflective of the actual user experience? I see in that link, which looks like the actual levels to me, that WASD still controls the Agent.

If that's just a tester convenience then A-OK no problem. I think we over here were just under the impression that those links were reflective of the actual user experience where as this sort of link:
https://code-dot-org.github.io/craft/

was just a development / testing environment. Any clarification would be great if we happen to be mixed up here 👍

**Comment by Hamms** [comment]
Oh, my bad! I clearly should have looked at the link more carefully. You are correct that levelbuilder-studio links are indeed reflective of the actual user experience. My apologies for the confusion

**Comment by WilliamHarmonMS** [comment]
Thanks my dude! @v-samtha just so you're aware.

**Comment by WilliamHarmonMS** [comment]
This fix as gone live
