### ISSUE TITLE
"Optimized" assets look worse in production than other environments

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#346]
https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/6

![image](https://user-images.githubusercontent.com/413693/31792282-5739b6ea-b4d0-11e7-955c-541ea27cca65.png)

https://studio.code.org/s/craft17/stage/1/puzzle/6

![image](https://user-images.githubusercontent.com/413693/31792296-6226c20a-b4d0-11e7-874f-1c0146b1b0b6.png)

**Comment by ryansloan** [comment]
@WilliamHarmonMS Will run this by Joel for sign-off. If needed we can selectively opt out of optimization here.

**Comment by WilliamHarmonMS** [comment]
"Oh yeah, gross. 😄 
I would say they should.
If it is something about png size I can use a file crusher, but they are changing from png 24 to web restricted gif or something causing all the dithering (dot patterns) and flat transparency (bad shadows - see plants).
When you talk to them, make sure they disable it for all years, because it is currently deployed to 2015 and 2016 games live... 😞 "

~Joel (paraphrased)

It looks like we definitely want to disable that if we can?

**Comment by ryansloan** [comment]
[PR 17631 in code-dot-org repo](https://github.com/code-dot-org/code-dot-org/pull/18731/files) should take care of this.
