### ISSUE TITLE
Level 10 - Torches do not light the area they are in correctly.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#374]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10

This is a polish issue. The lighting does not look correct when shadows are cast in an area that a torch is currently occupying. 

Repro Steps:
1) Start level 10.
2) Observe the shadows being cast in the torch occupied positions.

Expected Results:
Locations with Torches do not have shadows in the same location.

Actual Results:
Shadows remain in locations with torches.

Video:
[TorchLightPolish.zip](https://github.com/code-dot-org/craft/files/1412416/TorchLightPolish.zip)

**Comment by WilliamHarmonMS** [comment]
"Torches are block light, which are for visibility, and defining light levels in the world for mob spawning. They don't cast shadows, they clear Fog of war. The shadows are for defining 3D space.

That said, I would say the better solution for this is to remove the torches and make the portal a light source that clears Fog of war, since it does emit light in minecraft."

~Joel
